# Generated by Django 5.1.6 on 2025-03-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField()),
                ('detalle', models.TextField()),
                ('foto', models.ImageField(upload_to='noticias/')),
                ('publicada', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
